fail_fast: true
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.1.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-case-conflict
      - id: check-docstring-first
      - id: check-json
      - id: check-added-large-files
      - id: check-merge-conflict
      - id: check-yaml
      - id: debug-statements
      - id: name-tests-test
#      - id: double-quote-string-fixer
      - id: requirements-txt-fixer

  - repo: https://github.com/ambv/black
    rev: "22.3.0"
    hooks:
      - id: black
#        name: black
        language_version: python3.9
        stages: [commit]
        entry: black
        types: [python]

  - repo: https://github.com/pycqa/flake8
    rev: '4.0.1'
    hooks:
      - id: flake8
        name: flake8
        stages: [commit]
        language: system
        entry: flake8
        types: [python]
        args: [--ignore, "W503,E203"]

  - repo: https://github.com/pre-commit/mirrors-pylint
    rev: 'v3.0.0a4'
    hooks:
    - id: pylint
      stages: [commit]
      files: \.py$
      language: system
      types: [python]
#      args: [-E]
#      args: [-E,--extension-pkg-whitelist,'pydantic',--disable,"no-self-argument,C,W"]
      args: [--extension-pkg-whitelist,'pydantic',--disable,'C,R,W']
#      pass_filenames: false
#      language: python
#      language_version: python3.9
#      additional_dependencies: [-r, requirements.txt]
